### ISSUE TITLE
Find a "person" logo.   "admin" button is labeled with user.username

### ISSUE THREAD

**Issue by PeregrineTEL** [PeregrineTEL/TEKDB#24]
- [x] checkout out Bootstrap's built-in glyphicons -- see 'glyphicon-user'

Is this intentional? I see "admin" because that is my user name. Do we want everyone to see their user name? Or, should they see a more generic label. ("admin" for everyone? Unless a user is staff, they won't see "Administration" in the drop-down -- only "Logout".

Relevant code from navbar.hmtl (lines 56-70): 
`{% if user.is_authenticated %}
      <div class="dropdown col-sm-3 col-md-3">
        <button class="btn dropdown-toggle" type="button" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          {{ user.username }}
        </button>
        <ul class="dropdown-menu" aria-labelledby="userDropdown">
          {% if user.is_staff %}
          <li><a class="dropdown-item" href="/admin">Administration</a></li>
          {% endif %}
          <li><a class="dropdown-item" href="/logout?next=/">Logout</a></li>
        </ul>
      </div>
      {% else %}
      <a class="col-sm-3 col-md-3 header-button" data-toggle="modal" data-target="#loginModal">
        Login`

**Comment by rhodges** [comment]
This is very intentional.
This is a 'my account' button, not an 'admin' button.
Currently the only broad 'my account' action available is 'logout'.

Because you are logged in as an administrator, you see the 'Administration' link, which is the only part of the tool that should consistently indicate an access point for administration. 

If this is unclear (and not just because you are logged in as a user named 'Admin') you are welcome to look into adding a 'person' logo (I recomend checkout out [Bootstrap's built-in glyphicons](https://getbootstrap.com/docs/3.3/components/)  -- see 'glyphicon-user' )
