### ISSUE TITLE
Create a GitHub project board? 

### ISSUE THREAD

**Issue by PeregrineTEL** [PeregrineTEL/TEKDB#27]

**Comment by rhodges** [comment]
I don't see that there is much call for this for a single repository. I find GitHub 'Projects' to be helpful in coordinating a workflow that requires coordinating issues between different repositories. 

That being said, there are numerous features of GitHub projects, more than I can claim to be familiar with. If you see a particular feature that would benefit this project then by all means, use whatever tools are at your disposal.

A note on tools: Software development and Engineering  a fields that are super-saturated with tools, productivity, process, and others. No one person is expected to master all of them (or even a majority, or even a large minority), and it would be inefficient to do so. The more successful shops adopt a few core tools that all developers and engineers adhere to, then when as new tools come out, workers can adopt them into their personal workflow if it does not interfere with maximizing the efficiency of the current team workflow. If these tools begin to be accepted by multiple team-members, then the tool is evaluated for how it can be introduced into the team workflow.

Checking out other tools on your time is encouraged. Using some work time (5-7%) to review promising tools to fix a known gap in the current process is also encouraged. However I do know developers that have fallen into the trap of constantly adopting and testing and learning new tools leaving a trail of failed projects that cannot be maintained due to a jigsaw puzzle of external dependencies and jumbled documentation.
